name: movies_shared
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  dart_mappable: ^1.0.0-dev.5

dev_dependencies:
  build_runner: ^2.1.8
  lints: ^1.0.0
  test: ^1.16.0
