name: movies_backend
description: A server app using the shelf package and Docker.

publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  movies_shared:
    path: ../movies_shared
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_hotreload: ^1.1.0

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
